/* Editorial redesign for product pages; all numeric telemetry remains API-backed. */
(function () {
  const storyCopy = {
    ru: {
      stamp:'X / ПЛАТФОРМА В ПРОЗРАЧНОМ РАЗРЕЗЕ', hero:'Сначала — человек. Потом — данные.', lead:'Xylen не угадывает, что происходит с телефоном. Клиент отправляет отчёт с согласия; платформа показывает его путь и точно обозначает, где заканчиваются доступные сведения.', ticker:'СОГЛАСИЕ · ОТЧЁТ · СВОДКА · КОНТРОЛЬ ДОСТУПА ·', index:['Зачем создана','Как проходит отчёт','Границы системы','Конфиденциальность'],
      chapters:[['01 / НАЗНАЧЕНИЕ','Порядок вместо шума','Веб-панель помогает владельцу читать события приложения и присланные Android счётчики как один связный журнал. Она отделяет общую картину от подробных записей и показывает, когда отчёт поступил.','Это не радар и не скрытая служба наблюдения. Значения приходят от приложения и могут отражать состояние только в момент формирования конкретного отчёта.'],['02 / МАРШРУТ','Один отчёт. Четыре границы.','Пользователь разрешает отправку. Android формирует JSON-событие. API принимает и сохраняет сведения в настроенном хранилище. Публичная сводка выдаёт агрегат, а владелец проходит отдельную проверку для просмотра подробностей.','Если отчёт не отправлялся, система не заполняет пробел вымышленными измерениями. Если графику не хватает временных точек, он прямо сообщает, что данных пока нет.'],['03 / ТЕХНИЧЕСКИЙ СЛОЙ','Что видит веб-платформа','Отчёт может включать ID установки, модель, выбранное в клиенте имя тестировщика, экран, действие, детали, время, оператора, мобильные счётчики и сведения о SIM-профилях, которые формирует клиент.','API сайта принимает JSON через /api/audit. Публичная сводка содержит агрегированные счётчики. Подробные события выдаются отдельным маршрутом после проверки Cloudflare Access и совпадения email владельца.'],['04 / ПРИНЦИП','Клиент сообщает. Сервер отображает.','Сервер не проверяет независимо, верно ли устройство посчитало счётчик. Поэтому интерфейс должен называть данные клиентскими показаниями и сопровождать их временем получения, а не выдавать за лабораторное измерение.','iOS в проверенной версии приложения хранит журнал локально. Android portal API — отдельный поток со своим адресом и настройкой ключа; он не является веб audit API этой панели.']],
      privacyTitle:'Конфиденциальность — крупным шрифтом и без мелкого обещания.', privacyLead:'Ниже — подробное описание данных, их пути, доступа и ограничений хранения в изученных версиях проекта. Это техническое описание, а не юридическое заключение или сертификат соответствия.', privacyMore:'ПОДРОБНЫЙ РАЗБОР · ПРОКРУТИТЕ НИЖЕ', faqTitle:'Что важно знать до подключения', faqs:[['Согласие отключено — что происходит?','Клиент прекращает будущую отправку. Уже принятые сервером записи автоматически от этого не удаляются.'],['Публичная сводка показывает телефон или SIM?','Нет. Она возвращает агрегированные числа. Подробные SIM-поля доступны только владельцу после проверки доступа.'],['Счётчик мобильной загрузки проверен оператором?','Нет. Его присылает клиент; сайт не сверяет его с биллинговой записью оператора.'],['Где хранится журнал?','Постоянное хранение зависит от настроенного Cloudflare KV binding и процедур владельца проекта. Не заявляйте местонахождение данных без отдельной проверки конфигурации.']],
      devicesEyebrow:'ПРИЁМ ОТЧЁТА · ANDROID',devicesTitle:'Сводка показывает приход. Не слежение.',devicesLead:'Счётчик появляется после получения клиентского отчёта. Значение «активен» означает недавнюю передачу в пределах окна API, а не постоянное соединение телефона с панелью.',deviceSteps:[['01','Отчёт получен','Время фиксируется на стороне сервера после передачи клиента.'],['02','Сводка обновлена','Открытая панель отображает агрегированные значения без SIM-профиля.'],['03','Детали закрыты','Подробный журнал доступен владельцу через Cloudflare Access.']],deviceNote:'Устройства без новых отчётов не исчезают в догадках: пустые и недоступные состояния показаны отдельно. Сайт не получает радиосигнал, CID/TAC или координаты.',
      trafficEyebrow:'СЧЁТЧИКИ · ПО ВРЕМЕНИ ПОЛУЧЕНИЯ',trafficTitle:'График строится из точек отчёта.',trafficLead:'Линия не имитирует непрерывный мониторинг. Каждая точка появляется только после полученного Android-отчёта с допустимыми данными и отметкой времени.',trafficFacts:[['СУММА','Клиентские байты','Суммарный мобильный счётчик, переданный приложением. Сверки с биллингом оператора нет.'],['СОБЫТИЯ','Журнал отчётов','Показывает число сохранённых событий в пределах ограниченного серверного журнала.'],['СКОРОСТЬ','Не передаётся','Текущая скорость радиоэфира не является полем веб audit API и поэтому не рисуется.']],trafficNote:'Нет точек за период — нет линии. Это полезный ответ: он отделяет отсутствие отчётов от нулевого расхода.',
      releaseEyebrow:'КЛИЕНТЫ · ССЫЛКИ НА СБОРКИ',releaseTitle:'Выберите платформу. Проверьте источник.',releaseLead:'На этой странице находятся только ссылки на пакеты, уже указанные в проекте. Совместимость, подпись и состав сборки следует сверить перед установкой; интерфейс не присваивает пакету неподтверждённую версию.',android:'ANDROID',ios:'iOS',download:'Открыть ссылку пакета',qr:'Показать QR-код',archive:'Другие ссылки в архиве',releaseCaution:'Установка пакета зависит от ОС, подписи приложения, политик устройства и источника распространения. Не выдавайте это описание за подтверждение публикации в магазине приложений.',releasePoints:[['Проверьте источник','Сверьте адрес пакета с владельцем проекта перед установкой.'],['Сверьте платформу','APK предназначен для Android; IPA сам по себе не гарантирует возможность установки на iPhone.'],['Читайте запросы ОС','Выдавайте только те разрешения, которые объяснены внутри клиента и действительно нужны вам.']],about:'О платформе',privacy:'Конфиденциальность',open:'Открыть раздел',notLinked:'Ссылка на пакет в проекте не указана.'
    },
    en: {
      stamp:'X / THE PLATFORM, IN THE OPEN', hero:'People first. Data second.', lead:'Xylen does not guess what happens on a phone. A client sends a report with consent; the platform shows its path and states exactly where its information ends.', ticker:'CONSENT · REPORT · SUMMARY · ACCESS CONTROL ·', index:['Purpose','Report path','System boundaries','Privacy'],
      chapters:[['01 / PURPOSE','Structure instead of noise','The web console helps an owner read app events and Android counters as one coherent report history. It separates the public picture from detailed records and shows when a report arrived.','This is not a radar or hidden tracking service. Values come from the app and may represent only the moment a particular report was created.'],['02 / ROUTE','One report. Four boundaries.','The user allows reporting. Android creates a JSON event. The API accepts and stores information in the configured storage. The public summary returns aggregates, while the owner completes a separate check to view detail.','If no report was sent, the system does not fill the gap with invented measurements. If a chart lacks timestamped points, it says that data is not available yet.'],['03 / TECHNICAL LAYER','What the web platform can see','A report may include an install ID, model, tester name entered in the client, screen, action, details, time, carrier, cellular counters, and SIM-profile fields produced by the client.','The site API accepts JSON through /api/audit. The public summary contains aggregate counters. Detailed events use a separate route after Cloudflare Access verification and a matching owner email.'],['04 / PRINCIPLE','The client reports. The server displays.','The server does not independently verify whether a device counted a counter correctly. The interface should call these client-reported readings and show their receipt time, not present them as lab measurements.','The reviewed iOS version keeps its activity log locally. Android portal API is a separate flow with its own address and key configuration; it is not this console’s web audit API.']],
      privacyTitle:'Privacy, in large type and without fine-print promises.', privacyLead:'A detailed account of data, its route, access, and storage boundaries in the reviewed project versions. This is a technical description, not legal advice or a compliance certificate.', privacyMore:'FULL EXPLANATION · CONTINUE BELOW', faqTitle:'Before you connect a client', faqs:[['What happens when consent is turned off?','The client stops future uploads. Records already accepted by the server are not automatically deleted.'],['Does the public summary expose a phone or SIM profile?','No. It returns aggregate counts. Detailed SIM fields are owner-only after access verification.'],['Are cellular counters verified by the carrier?','No. The client reports them; the site does not compare them with a carrier billing record.'],['Where is the log stored?','Persistent storage depends on the configured Cloudflare KV binding and the project owner’s procedures. Do not claim a data location without checking the configuration.']],
      devicesEyebrow:'REPORT INTAKE · ANDROID',devicesTitle:'A summary shows receipt, not surveillance.',devicesLead:'A counter appears after a client report arrives. “Active” means a recent report within the API window, not a continuous phone connection to the console.',deviceSteps:[['01','Report received','The server records receipt time after the client submits.'],['02','Summary updated','The public console shows aggregate values without a SIM profile.'],['03','Details protected','The owner opens detailed logs through Cloudflare Access.']],deviceNote:'Devices without new reports are not filled in by guesswork: empty and unavailable states are distinct. The site does not receive radio signal, CID/TAC, or coordinates.',
      trafficEyebrow:'COUNTERS · BY REPORT TIME',trafficTitle:'The chart is made of report points.',trafficLead:'The line does not imitate continuous monitoring. A point appears only after an Android report arrives with usable data and a timestamp.',trafficFacts:[['TOTAL','Client-reported bytes','A summed cellular counter submitted by the app. It is not reconciled against carrier billing.'],['EVENTS','Report log','Shows the number of retained events within the server log limit.'],['SPEED','Not reported','Live radio speed is not a web audit API field, so the chart does not draw it.']],trafficNote:'No points for a period means no line. That separates missing reports from zero usage.',
      releaseEyebrow:'CLIENTS · PACKAGE LINKS',releaseTitle:'Choose a platform. Verify the source.',releaseLead:'This page contains only package links already present in the project. Check compatibility, signing, and package contents before installation; the interface does not assign an unverified version.',android:'ANDROID',ios:'iOS',download:'Open package link',qr:'Show QR code',archive:'Other archive links',releaseCaution:'Installation depends on OS, app signing, device policies, and distribution source. This description does not confirm publication in an app store.',releasePoints:[['Verify the source','Confirm the package address with the project owner before installing.'],['Check the platform','An APK is for Android; an IPA alone does not guarantee iPhone installation.'],['Read OS prompts','Grant only permissions explained inside the client and needed by you.']],about:'About the platform',privacy:'Privacy',open:'Open section',notLinked:'No package link is configured in the project.'
    },
    uz: {
      stamp:'X / PLATFORMA OCHIQ KO‘RINISHDA', hero:'Avval inson. Keyin — ma’lumot.', lead:'Xylen telefonda nima bo‘layotganini taxmin qilmaydi. Mijoz rozilik bilan hisobot yuboradi; platforma uning yo‘lini ko‘rsatib, ma’lumot chegaralarini aniq belgilaydi.', ticker:'ROZILIK · HISOBOT · JAMLAMA · KIRISH NAZORATI ·', index:['Maqsad','Hisobot yo‘li','Chegaralar','Maxfiylik'],
      chapters:[['01 / MAQSAD','Shovqin o‘rniga tartib','Veb panel egaga ilova hodisalari va Android hisoblagichlarini yagona hisobot tarixi sifatida ko‘rishga yordam beradi. Ochiq jamlanmani batafsil yozuvlardan ajratadi va hisobot qachon kelganini ko‘rsatadi.','Bu radar yoki yashirin kuzatuv xizmati emas. Qiymatlar ilovadan keladi va faqat muayyan hisobot yaratilgan paytni aks ettirishi mumkin.'],['02 / YO‘L','Bitta hisobot. To‘rtta chegara.','Foydalanuvchi yuborishga rozilik beradi. Android JSON hodisasini yaratadi. API ma’lumotni sozlangan omborga qabul qiladi. Ochiq jamlanma umumiy sonlarni beradi, egasi esa batafsil ma’lumot uchun alohida tekshiruvdan o‘tadi.','Hisobot bo‘lmasa tizim bo‘shliqni o‘ylab topilgan o‘lchov bilan to‘ldirmaydi. Grafikda vaqt belgili nuqtalar bo‘lmasa, bu holat ochiq ko‘rsatiladi.'],['03 / TEXNIK QATLAM','Veb platforma nimani ko‘radi','Hisobotda o‘rnatish IDsi, model, mijozda kiritilgan sinovchi ismi, ekran, amal, tafsilot, vaqt, operator, mobil hisoblagichlar va mijoz tuzgan SIM profil maydonlari bo‘lishi mumkin.','Sayt API JSONni /api/audit orqali qabul qiladi. Ochiq jamlanma umumiy hisoblagichlarni qaytaradi. Batafsil hodisalar Cloudflare Access va egasi emaili tekshirilgan alohida yo‘l orqali olinadi.'],['04 / TAMOYIL','Mijoz yuboradi. Server ko‘rsatadi.','Server qurilma hisoblagichni to‘g‘ri hisoblaganini mustaqil tekshirmaydi. Shu sabab interfeys qiymatlarni mijoz yuborgan ko‘rsatkich deb atab, qabul qilingan vaqtni ko‘rsatishi kerak.','Ko‘rib chiqilgan iOS versiyasi jurnalni mahalliy saqlaydi. Android portal API alohida manzil va kalit sozlamasiga ega; u ushbu panelning veb audit APIsi emas.']],
      privacyTitle:'Maxfiylik — katta shrift bilan, yashirin va’dalarsiz.', privacyLead:'Ko‘rib chiqilgan loyiha versiyalarida ma’lumot, uning yo‘li, kirish va saqlash chegaralarining batafsil bayoni. Bu texnik ma’lumot, yuridik maslahat yoki muvofiqlik sertifikati emas.', privacyMore:'BATAFSIL TAHLIL · PASTGA DAVOM ETING', faqTitle:'Mijozni ulashdan oldin', faqs:[['Rozilik o‘chirilsa nima bo‘ladi?','Mijoz keyingi yuborishlarni to‘xtatadi. Server oldin qabul qilgan yozuvlar avtomatik o‘chirilmaydi.'],['Ochiq jamlanmada telefon yoki SIM ko‘rinadimi?','Yo‘q. U umumiy sonlarni qaytaradi. Batafsil SIM maydonlari kirish tekshiruvidan keyin egasiga ochiq.'],['Mobil hisoblagich operator tomonidan tekshiriladimi?','Yo‘q. Uni mijoz yuboradi; sayt operator hisob-fakturasi bilan solishtirmaydi.'],['Jurnal qayerda saqlanadi?','Doimiy saqlash Cloudflare KV sozlamasi va loyiha egasining jarayonlariga bog‘liq. Konfiguratsiyani tekshirmasdan joylashuvni da’vo qilmang.']],
      devicesEyebrow:'HISOBOTNI QABUL QILISH · ANDROID',devicesTitle:'Jamlanma qabulni ko‘rsatadi, kuzatuvni emas.',devicesLead:'Hisoblagich mijoz hisoboti kelgach ko‘rinadi. “Faol” degani API vaqt oralig‘ida yaqinda hisobot kelganini anglatadi, telefonga uzluksiz ulanishni emas.',deviceSteps:[['01','Hisobot keldi','Mijoz yuborganidan so‘ng server qabul qilingan vaqtni qayd etadi.'],['02','Jamlanma yangilandi','Ochiq panel SIM profilisiz umumiy qiymatlarni ko‘rsatadi.'],['03','Batafsil ma’lumot himoyalangan','Egasi batafsil jurnalni Cloudflare Access orqali ochadi.']],deviceNote:'Yangi hisobot yubormagan qurilmalar taxmin bilan to‘ldirilmaydi: bo‘sh holat va serverga ulanmaslik alohida ko‘rsatiladi. Sayt radio signal, CID/TAC yoki koordinatalarni olmaydi.',
      trafficEyebrow:'HISOBLAGICHLAR · HISOBOT VAQTI BO‘YICHA',trafficTitle:'Grafik hisobot nuqtalaridan tuziladi.',trafficLead:'Chiziq uzluksiz kuzatuvni taqlid qilmaydi. Nuqta faqat foydali ma’lumot va vaqt belgisi bo‘lgan Android hisoboti kelgach paydo bo‘ladi.',trafficFacts:[['JAMI','Mijoz yuborgan baytlar','Ilova yuborgan mobil hisoblagichlar yig‘indisi. Operator hisob-fakturasi bilan solishtirilmaydi.'],['HODISALAR','Hisobot jurnali','Server jurnalidagi saqlanayotgan hodisalar sonini ko‘rsatadi.'],['TEZLIK','Yuborilmaydi','Jonli radio tezligi veb audit API maydoni emas, shu sabab grafik uni chizmaydi.']],trafficNote:'Davr uchun nuqtalar yo‘q bo‘lsa, chiziq ham bo‘lmaydi. Bu hisobot yo‘qligini nol sarfdan ajratadi.',
      releaseEyebrow:'MIJOZLAR · PAKET HAVOLALARI',releaseTitle:'Platformani tanlang. Manbani tekshiring.',releaseLead:'Bu sahifada faqat loyihada ko‘rsatilgan paket havolalari bor. O‘rnatishdan oldin moslik, imzo va paket tarkibini tekshiring; interfeys tasdiqlanmagan versiyani bermaydi.',android:'ANDROID',ios:'iOS',download:'Paket havolasini ochish',qr:'QR kodni ko‘rsatish',archive:'Arxivdagi boshqa havolalar',releaseCaution:'O‘rnatish imkoniyati OT, ilova imzosi, qurilma siyosati va tarqatish manbasiga bog‘liq. Bu tavsif ilova do‘konida e’lon qilinganini tasdiqlamaydi.',releasePoints:[['Manbani tekshiring','O‘rnatishdan oldin paket manzilini loyiha egasi bilan tasdiqlang.'],['Platformani tekshiring','APK Android uchun; IPA fayli iPhone’da o‘rnatilishini o‘zi kafolatlamaydi.'],['OT so‘rovlarini o‘qing','Faqat mijoz ichida tushuntirilgan va sizga kerak ruxsatlarni bering.']],about:'Platforma haqida',privacy:'Maxfiylik',open:'Bo‘limni ochish',notLinked:'Loyihada paket havolasi ko‘rsatilmagan.'
    }
  };

  const packageLinks = (() => {
    const links = Array.from(document.querySelectorAll('#page-releases a[href]'))
      .map(anchor => ({ href: anchor.href, type: /\.apk(?:$|[?#])/i.test(anchor.href) ? 'android' : /\.ipa(?:$|[?#])/i.test(anchor.href) ? 'ios' : null }))
      .filter(item => item.type);
    return { android: links.filter(item => item.type === 'android'), ios: links.filter(item => item.type === 'ios') };
  })();

  function language() { return window.i18n?.currentLang || 'ru'; }
  function esc(value) { return String(value || '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])); }
  function sectionTexts(selector) {
    const card = document.querySelector(selector);
    return {
      intro: card?.querySelector('.about-body-text, .section-desc')?.textContent.trim() || '',
      title: card?.querySelector('.section-heading')?.textContent.trim() || '',
      articles: Array.from(card?.querySelectorAll('.info-article, .legal-article-block') || []).map(article => ({
        title: article.querySelector('h2')?.textContent.trim() || '',
        body: Array.from(article.querySelectorAll('p')).map(p => p.textContent.trim())
      }))
    };
  }

  function observeEditorial(root) {
    const targets = root.querySelectorAll('.editorial-reveal');
    if (matchMedia('(prefers-reduced-motion: reduce)').matches || !('IntersectionObserver' in window)) {
      targets.forEach(node => node.classList.add('is-visible'));
      return;
    }
    const observer = new IntersectionObserver(entries => entries.forEach(entry => {
      if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); }
    }), { threshold: 0.12, rootMargin: '0px 0px -5% 0px' });
    targets.forEach(node => observer.observe(node));
  }

  function renderAbout() {
    const t = storyCopy[language()] || storyCopy.ru;
    const page = document.getElementById('page-about');
    const about = page?.querySelector('.about-clean-card');
    const privacy = document.querySelector('#page-privacy .privacy-clean-card');
    if (!about || !privacy) return;
    const base = sectionTexts('#page-about .about-clean-card');
    const legal = sectionTexts('#page-privacy .privacy-clean-card');
    const systemChapters = t.chapters.map((chapter, i) => `
      <article class="about-chapter editorial-reveal" id="about-chapter-${i + 1}">
        <div class="about-chapter-index"><span>${chapter[0].split(' / ')[0]}</span><i></i><small>${chapter[0].split(' / ')[1]}</small></div>
        <div class="about-chapter-copy"><h3>${chapter[1]}</h3><p class="about-chapter-lead">${chapter[2]}</p><p>${chapter[3]}</p>${base.articles[i] ? `<p class="about-source-note"><b>${esc(base.articles[i].title)}:</b> ${esc(base.articles[i].body[0] || '')}</p>` : ''}</div>
      </article>`).join('');
    const privacySections = legal.articles.map((article, i) => `
      <article class="privacy-chapter editorial-reveal"><span class="privacy-chapter-no">0${i + 1}</span><div><span class="privacy-chapter-tag">${t.privacyMore}</span><h3>${esc(article.title)}</h3>${article.body.map((paragraph, j) => `<p class="${j === 0 ? 'privacy-chapter-lead' : ''}">${esc(paragraph)}</p>`).join('')}</div></article>`).join('');
    const faq = t.faqs.map((item, i) => `<details class="about-answer"><summary><span>0${i + 1}</span>${item[0]}<b aria-hidden="true">+</b></summary><p>${item[1]}</p></details>`).join('');
    about.innerHTML = `
      <div class="about-book">
        <section class="about-grand-hero">
          <div class="about-coordinate" aria-hidden="true"><span>XYLEN / FIELD NOTES</span><span>01—04 · ${language().toUpperCase()}</span></div>
          <span class="about-overline">${t.stamp}</span>
          <h1>${t.hero.split('. ').map((part, i) => `<span class="about-hero-line" style="--line:${i}">${part}${i === 0 ? '.' : ''}</span>`).join('')}</h1>
          <p class="about-grand-lead">${t.lead}</p>
          <div class="about-hero-foot"><span>01 — 04</span><span>${base.title}</span><span class="about-scroll-cue">↓</span></div>
          <div class="about-hero-orbit" aria-hidden="true"><i></i><i></i><i></i><b>X</b></div>
        </section>
        <div class="about-ticker" aria-hidden="true"><span>${t.ticker.repeat(3)}</span><span>${t.ticker.repeat(3)}</span></div>
        <nav class="about-index" aria-label="${t.about}">${t.index.map((item, i) => `<a href="#${i === 3 ? 'about-privacy' : `about-chapter-${i + 1}`}" class="about-index-link"><span>0${i + 1}</span>${item}<b aria-hidden="true">↘</b></a>`).join('')}</nav>
        <section class="about-manifesto editorial-reveal"><span class="about-giant-index">01</span><p class="about-manifesto-text">${language() === 'ru' ? 'Данные должны рассказывать правду о том, что было отправлено. Не придумывать то, чего клиент не сообщил.' : language() === 'uz' ? 'Ma’lumot yuborilgan narsani rost ko‘rsatishi kerak. Mijoz yubormagan narsani o‘ylab topmasligi kerak.' : 'Data should tell the truth about what was sent, never invent what the client did not report.'}</p><div class="about-manifesto-bottom"><span>${t.stamp}</span><span>01 / 04</span></div></section>
        <section class="about-chapter-list" id="about-architecture"><header class="about-section-heading editorial-reveal"><span>${t.index[0]} — ${t.index[2]}</span><h2>${language() === 'ru' ? 'Устройство доверия.' : language() === 'uz' ? 'Ishonch tuzilishi.' : 'The shape of trust.'}</h2><p>${base.intro}</p></header>${systemChapters}</section>
        <section class="about-interstitial editorial-reveal"><span>${language() === 'ru' ? 'ОДИН ПОТОК. РАЗНЫЕ УРОВНИ ДОСТУПА.' : language() === 'uz' ? 'BITTA OQIM. TURLI KIRISH DARAJALARI.' : 'ONE FLOW. DIFFERENT LEVELS OF ACCESS.'}</span><strong>${t.ticker.replaceAll(' · ', ' / ')}</strong><small>${language() === 'ru' ? 'Публичная сводка ≠ подробная запись' : language() === 'uz' ? 'Ochiq jamlanma ≠ batafsil yozuv' : 'Public summary ≠ detailed record'}</small></section>
        <section class="about-privacy-story" id="about-privacy"><header class="privacy-grand-heading editorial-reveal"><div class="privacy-index-art" aria-hidden="true"><span>02</span><i></i><i></i><i></i></div><div><span class="about-overline">${t.index[3]} / DATA CHARTER</span><h2>${t.privacyTitle}</h2><p>${legal.intro}</p></div></header><div class="privacy-story-intro editorial-reveal"><span>XYLEN / DATA NOTE 01—05</span><p>${t.privacyLead}</p></div><div class="privacy-chapters">${privacySections}</div><section class="about-privacy-faq editorial-reveal"><div class="about-faq-heading"><span>${t.faqTitle}</span><p>${language() === 'ru' ? 'Ответы опираются на текущую реализацию API и просмотренный код клиентов. Настройки проекта могут менять фактический маршрут.' : language() === 'uz' ? 'Javoblar APIning joriy ishlashi va ko‘rib chiqilgan mijoz kodiga asoslangan. Loyiha sozlamalari amaldagi yo‘lni o‘zgartirishi mumkin.' : 'Answers reflect the current API implementation and reviewed client source. Project settings can change the actual route.'}</p></div><div class="about-answer-list">${faq}</div></section></section>
        <footer class="about-endmark"><span>XYLEN</span><p>${language() === 'ru' ? 'Прозрачно по умолчанию.' : language() === 'uz' ? 'Shaffoflik — asosiy tamoyil.' : 'Transparent by design.'}</p><span>END / 04</span></footer>
      </div>`;
    privacy.closest('.container')?.setAttribute('aria-hidden', 'true');
    document.getElementById('page-privacy')?.setAttribute('hidden', '');
    observeEditorial(about);
  }

  function renderDevices() {
    const t = storyCopy[language()] || storyCopy.ru;
    const root = document.querySelector('#page-devices .devices-page');
    if (!root) return;
    root.querySelector('.device-editorial')?.remove();
    const markup = `<section class="device-editorial editorial-panel"><div class="editorial-panel-head"><span class="editorial-code">${t.devicesEyebrow}</span><span class="editorial-status"><i></i>${language() === 'ru' ? 'API-ОКНО · 75 СЕКУНД' : language() === 'uz' ? 'API ORALIG‘I · 75 SONIYA' : 'API WINDOW · 75 SECONDS'}</span></div><h2>${t.devicesTitle}</h2><p class="editorial-panel-lead">${t.devicesLead}</p><div class="device-route-grid">${t.deviceSteps.map((step, i) => `<article class="device-route-step editorial-reveal" style="--reveal-order:${i}"><span>${step[0]}</span><i class="device-route-connector" aria-hidden="true"></i><h3>${step[1]}</h3><p>${step[2]}</p></article>`).join('')}</div><div class="device-limit-note"><span class="limit-icon" aria-hidden="true">⌁</span><p>${t.deviceNote}</p><a href="#about-privacy" data-open-about>${t.privacy} <b>↗</b></a></div><div class="device-halo" aria-hidden="true"></div></section>`;
    const note = root.querySelector('.data-scope-note');
    if (note) note.insertAdjacentHTML('afterend', markup); else root.insertAdjacentHTML('beforeend', markup);
    observeEditorial(root);
    root.querySelector('[data-open-about]')?.addEventListener('click', event => { event.preventDefault(); window.switchPage('page-about'); setTimeout(() => document.getElementById('about-privacy')?.scrollIntoView({ behavior: 'smooth' }), 100); });
  }

  function renderTraffic() {
    const t = storyCopy[language()] || storyCopy.ru;
    const root = document.querySelector('#page-traffic .traffic-page');
    if (!root) return;
    root.querySelector('.traffic-editorial')?.remove();
    const chart = root.querySelector('.traffic-chart-card, .traffic-chart-panel, .traffic-chart-section') || root.querySelector('.traffic-chart-status')?.closest('section');
    const markup = `<section class="traffic-editorial editorial-panel"><div class="editorial-panel-head"><span class="editorial-code">${t.trafficEyebrow}</span><span class="traffic-wave-mark" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></span></div><h2>${t.trafficTitle}</h2><p class="editorial-panel-lead">${t.trafficLead}</p><div class="traffic-truth-grid">${t.trafficFacts.map((fact, i) => `<article class="traffic-truth-card editorial-reveal" style="--reveal-order:${i}"><span>0${i + 1} / ${fact[0]}</span><h3>${fact[1]}</h3><p>${fact[2]}</p><i aria-hidden="true"></i></article>`).join('')}</div><div class="traffic-no-data-note"><span class="no-data-orbit" aria-hidden="true"><i></i><i></i><i></i><b>—</b></span><p>${t.trafficNote}</p></div><a class="traffic-privacy-link" href="#about-privacy" data-open-about>${t.privacy}<span>↗</span></a></section>`;
    (chart || root.lastElementChild)?.insertAdjacentHTML('afterend', markup);
    observeEditorial(root);
    root.querySelector('[data-open-about]')?.addEventListener('click', event => { event.preventDefault(); window.switchPage('page-about'); setTimeout(() => document.getElementById('about-privacy')?.scrollIntoView({ behavior: 'smooth' }), 100); });
  }

  function renderReleases() {
    const t = storyCopy[language()] || storyCopy.ru;
    const page = document.getElementById('page-releases');
    const container = page?.querySelector('.container');
    if (!page || !container) return;
    const version = language();
    const apps = [
      { key:'android', name:t.android, icon:'assets/icon-android.svg', packages:packageLinks.android },
      { key:'ios', name:t.ios, icon:'assets/icon-ios.svg', packages:packageLinks.ios }
    ];
    const card = app => {
      const primary = app.packages[0];
      const available = primary ? `<a class="release-open" href="${esc(primary.href)}" target="_blank" rel="noopener noreferrer">${t.download}<b>↗</b></a><button class="release-qr" type="button" data-release-qr="${esc(primary.href)}" data-release-title="${esc(app.name)}">${t.qr}<span>▦</span></button>` : `<span class="release-unavailable">${t.notLinked}</span>`;
      return `<article class="release-editorial-card release-${app.key} editorial-reveal" style="--reveal-order:${app.key === 'android' ? 0 : 1}"><div class="release-card-top"><img src="${app.icon}" alt=""><span>${app.name}</span><span class="release-protocol">${app.key === 'android' ? 'APK' : 'IPA'}</span></div><div class="release-card-art" aria-hidden="true"><div class="release-art-grid"></div><div class="release-art-orbit"><i></i><i></i><i></i><b>${app.key === 'android' ? 'A' : 'i'}</b></div><span>XYLEN / CLIENT</span></div><h2>${app.key === 'android' ? (language() === 'ru' ? 'Клиент Android' : language() === 'uz' ? 'Android mijozi' : 'Android client') : (language() === 'ru' ? 'Клиент iOS' : language() === 'uz' ? 'iOS mijozi' : 'iOS client')}</h2><p>${app.key === 'android' ? (language() === 'ru' ? 'Отправка отчётов на веб-платформу работает только после согласия пользователя.' : language() === 'uz' ? 'Veb-platformaga hisobot yuborish faqat foydalanuvchi roziligidan so‘ng ishlaydi.' : 'Reports reach the web platform only after the user gives consent.') : (language() === 'ru' ? 'В проверенной версии журнала события остаются локально и на сайт не отправляются.' : language() === 'uz' ? 'Ko‘rib chiqilgan versiyada hodisalar jurnali mahalliy qoladi va saytga yuborilmaydi.' : 'In the reviewed version, the activity log stays local and is not sent to the site.')}</p><div class="release-card-actions">${available}</div></article>`;
    };
    const archive = [...packageLinks.android.slice(1).map((item, i) => ({...item, label:`${t.android} · ${i + 1}`})), ...packageLinks.ios.slice(1).map((item, i) => ({...item, label:`${t.ios} · ${i + 1}`}))];
    container.innerHTML = `<header class="releases-editorial-hero"><span class="editorial-code">${t.releaseEyebrow}</span><h1>${t.releaseTitle}</h1><p>${t.releaseLead}</p><div class="release-hero-stamp"><span>APK / IPA</span><i></i><span>XYLEN CLIENTS</span></div><div class="release-hero-number">02</div></header><div class="release-editorial-grid">${apps.map(card).join('')}</div><section class="release-install-notes"><header><span class="editorial-code">${language() === 'ru' ? 'ПЕРЕД УСТАНОВКОЙ' : language() === 'uz' ? 'O‘RNATISHDAN OLDIN' : 'BEFORE INSTALLATION'}</span><h2>${language() === 'ru' ? 'Три проверки. Никакой магии.' : language() === 'uz' ? 'Uch tekshiruv. Hech qanday sehr yo‘q.' : 'Three checks. No magic claims.'}</h2></header><div class="release-note-grid">${t.releasePoints.map((item, i) => `<article><span>0${i + 1}</span><h3>${item[0]}</h3><p>${item[1]}</p></article>`).join('')}</div><p class="release-caution">${t.releaseCaution}</p></section>${archive.length ? `<details class="release-archive"><summary><span>${t.archive}</span><b>${archive.length.toString().padStart(2,'0')}</b><i>+</i></summary><div>${archive.map((item,i)=>`<a href="${esc(item.href)}" target="_blank" rel="noopener noreferrer"><span>0${i+1}</span>${item.label}<b>↗</b></a>`).join('')}</div></details>` : ''}<a class="release-about-link" href="#about-privacy" data-open-about>${t.about} / ${t.privacy}<span>↗</span></a>`;
    container.querySelectorAll('[data-release-qr]').forEach(button => button.addEventListener('click', () => window.openQrModal?.(button.dataset.releaseQr, button.dataset.releaseTitle)));
    observeEditorial(container);
    container.querySelector('[data-open-about]')?.addEventListener('click', event => { event.preventDefault(); window.switchPage('page-about'); setTimeout(() => document.getElementById('about-privacy')?.scrollIntoView({ behavior: 'smooth' }), 100); });
  }

  function renderAll() { renderAbout(); renderDevices(); renderTraffic(); renderReleases(); }
  document.addEventListener('DOMContentLoaded', renderAll);
  window.addEventListener('xylen:lang-changed', renderAll);
})();
